import type { Metadata } from 'next';
import { Outfit } from 'next/font/google';
import '../globals.css';
import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer';
import { AuthProvider } from '@/context/AuthContext';

const outfitFont = Outfit({
  variable: '--font-outfit',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div
      className={`${outfitFont.variable} antialiased flex flex-col min-h-screen`}
    >
      <AuthProvider>
      <Navbar />
      <main className="flex-1">{children}</main>
      <Footer />
      </AuthProvider>
    </div>
  );
}
